name: taska
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl:
  image_picker:
  shared_preferences: ^2.0.12
  flutter_svg:

  cupertino_icons: ^1.0.2
  fluentui_system_icons: 1.1.223
  font_awesome_flutter: ^10.6.0
  google_fonts:


  dots_indicator: ^3.0.0
  flutter_holo_date_picker: 1.1.0
  calendar_date_picker2: ^0.5.3
  syncfusion_flutter_datepicker: ^24.1.41

  fl_country_code_picker: ^0.1.4
  pinput:
  carousel_slider:
  animated_bottom_navigation_bar:
  stylish_bottom_bar:
  loading_animation_widget: ^1.2.0+4
  percent_indicator:

  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_messaging:
  firebase_storage:


  multiple_stream_builder:
  connectivity:
  connectivity_plus:
  cached_network_image:
  buttons_tabbar: ^1.3.8

  get:
  uri:
  path:
  path_provider:
  http:
  logger:
#  custom_refresh_indicator: ^3.0.0
#  pull_to_refresh_flutter3: ^2.0.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/flag/
    - assets/background_images/