// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCntIee6XJ5MilWWgKe86bqntJ4-k11xyI',
    appId: '1:389481034909:web:eb99e5c9729988e8db9074',
    messagingSenderId: '389481034909',
    projectId: 'taska-e393e',
    authDomain: 'taska-e393e.firebaseapp.com',
    storageBucket: 'taska-e393e.appspot.com',
    measurementId: 'G-1N217SB4DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVSP2urlkl47YtCZVaZgfKAlIvrNNKA8Q',
    appId: '1:389481034909:android:41cd4ad5b2a81c0fdb9074',
    messagingSenderId: '389481034909',
    projectId: 'taska-e393e',
    storageBucket: 'taska-e393e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClImM7kIQG5WpWNPs_Nw599uvq1wBvy98',
    appId: '1:389481034909:ios:d1baf7615cf9eec1db9074',
    messagingSenderId: '389481034909',
    projectId: 'taska-e393e',
    storageBucket: 'taska-e393e.appspot.com',
    iosClientId: '389481034909-mmhc04amqq3d7j02dckjcu216mbt5d5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.taska',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClImM7kIQG5WpWNPs_Nw599uvq1wBvy98',
    appId: '1:389481034909:ios:83e88ad21535b0ffdb9074',
    messagingSenderId: '389481034909',
    projectId: 'taska-e393e',
    storageBucket: 'taska-e393e.appspot.com',
    iosClientId: '389481034909-ei9eqr739ghttlgdsfq4b2qqd62t3a5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.taska.RunnerTests',
  );
}
